spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    #    15672 ????????
    port: 5672
    virtual-host: /
    #  ???????????????
    publisher-confirm-type: correlated
    #    ??????
    publisher-returns: true
